import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ntogn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="min-h-max p-8 flex flex-col">
        <h1>Ntogn</h1>
      </main>

      <Footer />
    </>
  );
}
