import Head from 'next/head'
import Image from "next/image";

import BaseThumbRecord from "../components/BaseThumbRecord";
import Footer from "../components/Footer";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ntogn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-1 flex-col md:flex-row md:flex-wrap md:content-start">
        <BaseThumbRecord />
        <BaseThumbRecord />
        <BaseThumbRecord />
        <BaseThumbRecord />
        <BaseThumbRecord />
        <BaseThumbRecord />
        <BaseThumbRecord />
        <BaseThumbRecord />
      </main>
      <Footer />
    </>
  );
}
